# Generated by Django 4.2.7 on 2023-12-21 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MountainPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('other_titles', models.CharField(max_length=255)),
                ('connect', models.TextField(blank=True)),
                ('add_time', models.DateTimeField()),
                ('user', models.JSONField(default=dict)),
                ('coord', models.JSONField(default=dict)),
                ('level', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ImageField(upload_to='pass_image/')),
                ('title', models.CharField(max_length=255)),
                ('mountain_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mountapi.mountainpass')),
            ],
        ),
    ]
