# Generated by Django 4.2.7 on 2023-12-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mountainpass',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='image',
            name='data',
            field=models.ImageField(upload_to=''),
        ),
    ]
